### ISSUE TITLE
Hyprland cursor zoom (magnifier)

### ISSUE THREAD

**Issue by markfswe** [M1cha/dotfiles#1]
Hi! Thank you for making your dotfiles public :)

Could you please share `~/nbu/hyprctl-custom/target/release/hyprctl-custom` with me? Ideally source, but bin is ok. I don't really understand how can I change hyprland settings on-fly.

Found you as author of https://github.com/hyprwm/Hyprland/issues/2858

**Comment by M1cha** [comment]
I totally forgot to publish it, thanks for reminding me. Here you go: https://github.com/M1cha/hyprctl-custom. Binaries are also built and published automatically for every release: https://github.com/M1cha/hyprctl-custom/releases/tag/v0.1.0.

The main goal of that tool is to support everything that hyprctl doesn't and which cannot be implemented using a oneline bash script. Feel free to create PRs or issues with any additional features you need. I think next I'm gonna implement switching to the next/previous workspace since things get annoying when you go beyond workspace 9.

**Comment by ekhodx** [comment]
Thank you :) Is this a fork of hyprctl? I can suggest you listing features in readme, I won't create separate issue for this in that repo.

**Comment by ekhodx** [comment]
Also just want to let you know that hyprctl-custom works great with fusuma:
```
swipe:
  3:
    up:
      update:
        command: "~/.local/bin/hyprctl-custom cursor-zoom in"
    down:
      update:
        command: "~/.local/bin/hyprctl-custom cursor-zoom out"
interval:
  swipe: 0.2
```

I mostly use keyboard and trying to migrate to mouseless (touchpadless) life, but I appreciate the gestures when I am too lazy or just using laptop one handed.

The only thing I am missing is non-linear progression, some curve. Because the more you are zoomed in, the smaller next "step" feels. Hope you understood what I mean. But this already involves some config file I guess, which is not that easy, at least for me. Just my thoughts :)
